language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:ulikoehler/deb-buildscripts'
    packages:
    - gcc
    - g++
    - libssl-dev
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - libsnappy-dev
    - librocksdb

rust:
  - stable
matrix:
  include:
    - rust: nightly-2017-10-03
      env: FEATURE=clippy

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - RUSTFMT_VERS=0.9.0
  - CLIPPY_VERS=0.0.165
  - CARGO_INCREMENTAL=1
  - RUSTFLAGS="-C link-dead-code"
  - CODECOV_TOKEN=90006bf6-e4b7-4825-b880-8d19c4e21c21
  - ROCKSDB_LIB_DIR=$LD_LIBRARY_PATH
  - SNAPPY_LIB_DIR=$LD_LIBRARY_PATH
  matrix:
  - FEATURE=fmt
  - FEATURE=test-lib
  - FEATURE=test-doc

install:
- |
  case "$FEATURE" in
  clippy )
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  ;;
  esac
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cargo update
    fi
- cargo install --list
script: |
  case "$FEATURE" in
  "fmt" )
      cargo audit && cargo fmt -- --write-mode=diff
  ;;
  "clippy" )
      cargo clippy -- -D warnings
  ;;
  "test-lib" )
      RUST_LOG=off cargo test --tests --lib
  ;;
  "test-doc" )
      cargo test --doc -- --test-threads=2
  ;;
  esac